/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameproject;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Amrit
 */
public class MenuForm extends javax.swing.JFrame{
    JPanel cards;
    LeaderBoardDatabase database;
    /**
     * Creates new form GameGui
     */
    public MenuForm() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        parentPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        instructionButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        leaderboardPanel = new javax.swing.JPanel();
        playerNameTestField = new java.awt.TextField();
        menuButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        quitButton2 = new javax.swing.JButton();
        leaderboardTitleLabel = new javax.swing.JLabel();
        enterNameLabel = new javax.swing.JLabel();
        leaderboardTextPane = new javax.swing.JTextPane();
        questionPanel = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        currentQuestion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        currentPoints = new javax.swing.JTextPane();
        optionOne = new javax.swing.JRadioButton();
        optionTwo = new javax.swing.JRadioButton();
        optionThree = new javax.swing.JRadioButton();
        optionFour = new javax.swing.JRadioButton();
        lockAnswer = new javax.swing.JButton();
        nextQuesButton = new javax.swing.JButton();
        useLifeline = new javax.swing.JButton();
        quitButton4 = new javax.swing.JButton();
        lifelinePanel = new javax.swing.JPanel();
        lifelineLabel = new javax.swing.JLabel();
        fiftyfiftyOption = new javax.swing.JRadioButton();
        phoneOption = new javax.swing.JRadioButton();
        audienceOption = new javax.swing.JRadioButton();
        chooseLifelineButton = new javax.swing.JButton();
        backToQuestionButton = new javax.swing.JButton();
        quitButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gameEndPanel = new javax.swing.JPanel();
        gameEndLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        moneyWonLabel = new javax.swing.JLabel();
        moneyWonValue = new javax.swing.JLabel();
        quitButton3 = new javax.swing.JButton();
        menuButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who Wants To Be A Millionaire");
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(0, 0, 0));
        menuPanel.setMinimumSize(new java.awt.Dimension(663, 450));
        menuPanel.setPreferredSize(new java.awt.Dimension(663, 450));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/Logo_of_NZ_Millionaire.jpg"))); // NOI18N

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        instructionButton.setText("Instructions");
        instructionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(playButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instructionButton)
                .addGap(124, 124, 124)
                .addComponent(quitButton)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(55, 55, 55))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playButton)
                    .addComponent(instructionButton)
                    .addComponent(quitButton))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        parentPanel.add(menuPanel, "card2");

        leaderboardPanel.setBackground(new java.awt.Color(0, 0, 0));

        playerNameTestField.setName(""); // NOI18N
        playerNameTestField.setText("Name");
        playerNameTestField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerNameTestFieldFocusGained(evt);
            }
        });
        playerNameTestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameTestFieldActionPerformed(evt);
            }
        });

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        quitButton2.setText("Quit");
        quitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton2ActionPerformed(evt);
            }
        });

        leaderboardTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        leaderboardTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        leaderboardTitleLabel.setText("LEADERBOARD");

        enterNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterNameLabel.setForeground(new java.awt.Color(255, 204, 0));
        enterNameLabel.setText("Please input your name before clicking \"Start\"");

        leaderboardTextPane.setEditable(false);

        javax.swing.GroupLayout leaderboardPanelLayout = new javax.swing.GroupLayout(leaderboardPanel);
        leaderboardPanel.setLayout(leaderboardPanelLayout);
        leaderboardPanelLayout.setHorizontalGroup(
            leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leaderboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerNameTestField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(leaderboardPanelLayout.createSequentialGroup()
                .addGroup(leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leaderboardTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(leaderboardPanelLayout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(leaderboardTitleLabel))
                        .addGroup(leaderboardPanelLayout.createSequentialGroup()
                            .addGap(196, 196, 196)
                            .addComponent(enterNameLabel))
                        .addGroup(leaderboardPanelLayout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(menuButton)
                            .addGap(140, 140, 140)
                            .addComponent(startButton)
                            .addGap(136, 136, 136)
                            .addComponent(quitButton2))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        leaderboardPanelLayout.setVerticalGroup(
            leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderboardPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(leaderboardTitleLabel)
                .addGap(16, 16, 16)
                .addComponent(leaderboardTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterNameLabel)
                .addGap(13, 13, 13)
                .addComponent(playerNameTestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(startButton)
                    .addComponent(quitButton2))
                .addGap(41, 41, 41))
        );

        parentPanel.add(leaderboardPanel, "card3");

        questionPanel.setBackground(new java.awt.Color(0, 0, 0));

        questionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(255, 204, 0));
        questionLabel.setText("Your Question:");

        currentQuestion.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("You are on:");

        jScrollPane3.setViewportView(currentPoints);

        optionOne.setText("jRadioButton1");

        optionTwo.setText("jRadioButton1");

        optionThree.setText("jRadioButton1");

        optionFour.setText("jRadioButton1");

        lockAnswer.setText("Lock In");

        nextQuesButton.setText("Next");

        useLifeline.setText("Use Lifeline");
        useLifeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useLifelineActionPerformed(evt);
            }
        });

        quitButton4.setText("Quit");

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(optionOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optionTwo))
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(optionThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optionFour))
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(questionPanelLayout.createSequentialGroup()
                                .addComponent(useLifeline)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lockAnswer))
                            .addGroup(questionPanelLayout.createSequentialGroup()
                                .addComponent(nextQuesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quitButton4)))
                        .addGap(127, 127, 127)))
                .addGap(111, 111, 111))
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(questionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(currentQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(questionLabel)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(currentQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionOne)
                    .addComponent(optionTwo))
                .addGap(32, 32, 32)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionThree)
                    .addComponent(optionFour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lockAnswer)
                    .addComponent(useLifeline))
                .addGap(49, 49, 49)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextQuesButton)
                    .addComponent(quitButton4))
                .addGap(36, 36, 36))
        );

        parentPanel.add(questionPanel, "card4");

        lifelinePanel.setBackground(new java.awt.Color(0, 0, 0));

        lifelineLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lifelineLabel.setForeground(new java.awt.Color(255, 255, 255));
        lifelineLabel.setText("Life Line");

        fiftyfiftyOption.setText("50:50");

        phoneOption.setText("Phone A Friend");

        audienceOption.setText("Audience Vote");

        chooseLifelineButton.setText("Apply");

        backToQuestionButton.setText("Back");
        backToQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToQuestionButtonActionPerformed(evt);
            }
        });

        quitButton5.setText("Quit");
        quitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton5ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Choose a LifeLine and \"Apply\"");

        javax.swing.GroupLayout lifelinePanelLayout = new javax.swing.GroupLayout(lifelinePanel);
        lifelinePanel.setLayout(lifelinePanelLayout);
        lifelinePanelLayout.setHorizontalGroup(
            lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lifelinePanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(backToQuestionButton)
                .addGap(109, 109, 109)
                .addComponent(chooseLifelineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(quitButton5)
                .addGap(128, 128, 128))
            .addGroup(lifelinePanelLayout.createSequentialGroup()
                .addGroup(lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lifelinePanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lifelineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lifelinePanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneOption)
                            .addComponent(audienceOption)
                            .addComponent(fiftyfiftyOption)))
                    .addGroup(lifelinePanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lifelinePanelLayout.setVerticalGroup(
            lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lifelinePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lifelineLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(fiftyfiftyOption)
                .addGap(32, 32, 32)
                .addComponent(phoneOption)
                .addGap(33, 33, 33)
                .addComponent(audienceOption)
                .addGap(52, 52, 52)
                .addGroup(lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseLifelineButton)
                    .addComponent(backToQuestionButton)
                    .addComponent(quitButton5))
                .addGap(96, 96, 96))
        );

        parentPanel.add(lifelinePanel, "card6");

        gameEndPanel.setBackground(new java.awt.Color(0, 0, 0));

        gameEndLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        gameEndLabel.setForeground(new java.awt.Color(255, 204, 0));
        gameEndLabel.setText("GAME OVER/ You've won");

        jScrollPane2.setViewportView(jTextPane1);

        moneyWonLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        moneyWonLabel.setForeground(new java.awt.Color(255, 255, 255));
        moneyWonLabel.setText("You've Won: ");

        moneyWonValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        moneyWonValue.setForeground(new java.awt.Color(255, 255, 255));
        moneyWonValue.setText("jLabel2");

        quitButton3.setText("Quit");
        quitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton3ActionPerformed(evt);
            }
        });

        menuButton2.setText("Menu");
        menuButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameEndPanelLayout = new javax.swing.GroupLayout(gameEndPanel);
        gameEndPanel.setLayout(gameEndPanelLayout);
        gameEndPanelLayout.setHorizontalGroup(
            gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(menuButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitButton3)
                .addGap(165, 165, 165))
            .addGroup(gameEndPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(moneyWonLabel)
                .addGap(49, 49, 49)
                .addComponent(moneyWonValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                        .addComponent(gameEndLabel)
                        .addGap(102, 102, 102))))
        );
        gameEndPanelLayout.setVerticalGroup(
            gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameEndPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(gameEndLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyWonLabel)
                    .addComponent(moneyWonValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton3)
                    .addComponent(menuButton2))
                .addGap(25, 25, 25))
        );

        parentPanel.add(gameEndPanel, "card5");

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 440));
        parentPanel.getAccessibleContext().setAccessibleName("parentPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void instructionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionButtonActionPerformed
        JOptionPane.showMessageDialog(null, "- To answer a question please type the letter corresponding to the answer and hit enter.\n"
                + "- To use a lifeline, type \"YES\" when prompted and pick a lifeline from the lifelines shown.\n"
                + "- To walk away with the money, enter \"Q\" at any time and press enter.\n"
                + "- If you get an answer wrong, your money won will decrease to the corresponding thresholds (100, 1000, 32000).\n"
                + "- If you get a question wrong at the threshold, the game will end.\n"
                + "- If you're ready to become a millionaire, type \"START\" and hit enter.", "Instructions", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_instructionButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(leaderboardPanel);
        parentPanel.repaint();
        parentPanel.revalidate();

        //displaying text from database doesn't work
        try {
            leaderboardTextPane.setText("Order of Player:" + database.getDatabase()); 
        }catch (NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Leader Board could not be loaded");
        }
        
        
    }//GEN-LAST:event_playButtonActionPerformed

    private void quitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButton2ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void quitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButton3ActionPerformed

    private void menuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton2ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_menuButton2ActionPerformed

    private void useLifelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useLifelineActionPerformed
        parentPanel.removeAll();
        parentPanel.add(lifelinePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
       
    }//GEN-LAST:event_useLifelineActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (!playerNameTestField.getText().equalsIgnoreCase("") && !playerNameTestField.getText().equalsIgnoreCase("Name")){
            parentPanel.removeAll();
            parentPanel.add(questionPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
        }
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void backToQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToQuestionButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(questionPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_backToQuestionButtonActionPerformed

    private void quitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButton5ActionPerformed

    private void playerNameTestFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerNameTestFieldFocusGained
        playerNameTestField.setText("");
    }//GEN-LAST:event_playerNameTestFieldFocusGained

    private void playerNameTestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameTestFieldActionPerformed
        new GamePlay(playerNameTestField.getText());
    }//GEN-LAST:event_playerNameTestFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton audienceOption;
    private javax.swing.JButton backToQuestionButton;
    private javax.swing.JButton chooseLifelineButton;
    private javax.swing.JTextPane currentPoints;
    private javax.swing.JTextField currentQuestion;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JRadioButton fiftyfiftyOption;
    private javax.swing.JLabel gameEndLabel;
    private javax.swing.JPanel gameEndPanel;
    private javax.swing.JButton instructionButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel leaderboardPanel;
    private javax.swing.JTextPane leaderboardTextPane;
    private javax.swing.JLabel leaderboardTitleLabel;
    private javax.swing.JLabel lifelineLabel;
    private javax.swing.JPanel lifelinePanel;
    private javax.swing.JButton lockAnswer;
    private javax.swing.JLabel logo;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton menuButton2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel moneyWonLabel;
    private javax.swing.JLabel moneyWonValue;
    private javax.swing.JButton nextQuesButton;
    private javax.swing.JRadioButton optionFour;
    private javax.swing.JRadioButton optionOne;
    private javax.swing.JRadioButton optionThree;
    private javax.swing.JRadioButton optionTwo;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JRadioButton phoneOption;
    private javax.swing.JButton playButton;
    private java.awt.TextField playerNameTestField;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton quitButton2;
    private javax.swing.JButton quitButton3;
    private javax.swing.JButton quitButton4;
    private javax.swing.JButton quitButton5;
    private javax.swing.JButton startButton;
    private javax.swing.JButton useLifeline;
    // End of variables declaration//GEN-END:variables
}
