/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameproject;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javafx.scene.control.ToggleGroup;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Amrit
 */
public class MenuForm extends javax.swing.JFrame{
    JPanel cards;
    LeaderBoardDatabase database;
    GamePlay game;
    PlayerInfo player;
    CheckAnswer updateMoneyWon;
    /**
     * Creates new form GameGui
     */
    public MenuForm() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        
        //try move it back to GamePlay file
        game = new GamePlay();
        player = new PlayerInfo(playerNameTextField.getText(), 0);
        updateMoneyWon = new CheckAnswer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        parentPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        instructionButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        leaderboardPanel = new javax.swing.JPanel();
        playerNameTextField = new java.awt.TextField();
        menuButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        quitButton2 = new javax.swing.JButton();
        leaderboardTitleLabel = new javax.swing.JLabel();
        enterNameLabel = new javax.swing.JLabel();
        leaderboardTextPane = new javax.swing.JTextPane();
        questionPanel = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        currentQuestionTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        currentPointsTextPane = new javax.swing.JTextPane();
        optionA = new javax.swing.JRadioButton();
        optionB = new javax.swing.JRadioButton();
        optionC = new javax.swing.JRadioButton();
        optionD = new javax.swing.JRadioButton();
        lockAnswer = new javax.swing.JButton();
        nextQuesButton = new javax.swing.JButton();
        useLifeline = new javax.swing.JButton();
        quitButton4 = new javax.swing.JButton();
        lifelinePanel = new javax.swing.JPanel();
        lifelineLabel = new javax.swing.JLabel();
        fiftyfiftyOption = new javax.swing.JRadioButton();
        phoneOption = new javax.swing.JRadioButton();
        audienceOption = new javax.swing.JRadioButton();
        chooseLifelineButton = new javax.swing.JButton();
        backToQuestionButton = new javax.swing.JButton();
        quitButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gameEndPanel = new javax.swing.JPanel();
        gameEndLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        moneyWonLabel = new javax.swing.JLabel();
        moneyWonValue = new javax.swing.JLabel();
        quitButton3 = new javax.swing.JButton();
        menuButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who Wants To Be A Millionaire");
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(0, 0, 0));
        menuPanel.setMinimumSize(new java.awt.Dimension(663, 450));
        menuPanel.setPreferredSize(new java.awt.Dimension(663, 450));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/Logo_of_NZ_Millionaire.jpg"))); // NOI18N

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        instructionButton.setText("Instructions");
        instructionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(playButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instructionButton)
                .addGap(124, 124, 124)
                .addComponent(quitButton)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(55, 55, 55))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playButton)
                    .addComponent(instructionButton)
                    .addComponent(quitButton))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        parentPanel.add(menuPanel, "card2");

        leaderboardPanel.setBackground(new java.awt.Color(0, 0, 0));

        playerNameTextField.setName(""); // NOI18N
        playerNameTextField.setText("Name");
        playerNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playerNameTextFieldFocusGained(evt);
            }
        });
        playerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameTextFieldActionPerformed(evt);
            }
        });

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        quitButton2.setText("Quit");
        quitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton2ActionPerformed(evt);
            }
        });

        leaderboardTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        leaderboardTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        leaderboardTitleLabel.setText("LEADERBOARD");

        enterNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterNameLabel.setForeground(new java.awt.Color(255, 204, 0));
        enterNameLabel.setText("Please input your name before clicking \"Start\"");

        leaderboardTextPane.setEditable(false);

        javax.swing.GroupLayout leaderboardPanelLayout = new javax.swing.GroupLayout(leaderboardPanel);
        leaderboardPanel.setLayout(leaderboardPanelLayout);
        leaderboardPanelLayout.setHorizontalGroup(
            leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leaderboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(leaderboardPanelLayout.createSequentialGroup()
                .addGroup(leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leaderboardTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(leaderboardPanelLayout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(leaderboardTitleLabel))
                        .addGroup(leaderboardPanelLayout.createSequentialGroup()
                            .addGap(196, 196, 196)
                            .addComponent(enterNameLabel))
                        .addGroup(leaderboardPanelLayout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(menuButton)
                            .addGap(140, 140, 140)
                            .addComponent(startButton)
                            .addGap(136, 136, 136)
                            .addComponent(quitButton2))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        leaderboardPanelLayout.setVerticalGroup(
            leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderboardPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(leaderboardTitleLabel)
                .addGap(16, 16, 16)
                .addComponent(leaderboardTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterNameLabel)
                .addGap(13, 13, 13)
                .addComponent(playerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(startButton)
                    .addComponent(quitButton2))
                .addGap(41, 41, 41))
        );

        parentPanel.add(leaderboardPanel, "card3");

        questionPanel.setBackground(new java.awt.Color(255, 255, 255));

        questionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(255, 204, 0));
        questionLabel.setText("Your Question:");

        currentQuestionTextField.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("You are on:");

        jScrollPane3.setViewportView(currentPointsTextPane);

        buttonGroup1.add(optionA);
        optionA.setText("optionA");
        optionA.setMinimumSize(new java.awt.Dimension(100, 30));
        optionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionAActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionB);
        optionB.setText("optionB");
        optionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionC);
        optionC.setText("optionC");
        optionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionD);
        optionD.setText("optionD");
        optionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionDActionPerformed(evt);
            }
        });

        lockAnswer.setText("Lock In");
        lockAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockAnswerActionPerformed(evt);
            }
        });

        nextQuesButton.setText("Next");
        nextQuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuesButtonActionPerformed(evt);
            }
        });

        useLifeline.setText("Use Lifeline");
        useLifeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useLifelineActionPerformed(evt);
            }
        });

        quitButton4.setText("Quit");
        quitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(questionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(currentQuestionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))))
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionPanelLayout.createSequentialGroup()
                                .addComponent(useLifeline)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionPanelLayout.createSequentialGroup()
                                .addComponent(nextQuesButton)
                                .addGap(65, 65, 65)))
                        .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitButton4)
                            .addComponent(lockAnswer))
                        .addGap(238, 238, 238))
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(optionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optionB)
                        .addGap(188, 188, 188))
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(optionC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optionD)
                        .addGap(186, 186, 186))))
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(questionLabel)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(currentQuestionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionB))
                .addGap(32, 32, 32)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionC)
                    .addComponent(optionD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lockAnswer)
                    .addComponent(useLifeline))
                .addGap(18, 18, 18)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton4)
                    .addComponent(nextQuesButton))
                .addGap(47, 47, 47))
        );

        parentPanel.add(questionPanel, "card4");

        lifelinePanel.setBackground(new java.awt.Color(0, 0, 0));

        lifelineLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lifelineLabel.setForeground(new java.awt.Color(255, 255, 255));
        lifelineLabel.setText("Life Line");

        fiftyfiftyOption.setText("50:50");

        phoneOption.setText("Phone A Friend");

        audienceOption.setText("Audience Vote");

        chooseLifelineButton.setText("Apply");

        backToQuestionButton.setText("Back");
        backToQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToQuestionButtonActionPerformed(evt);
            }
        });

        quitButton5.setText("Quit");
        quitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton5ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Choose a LifeLine and \"Apply\"");

        javax.swing.GroupLayout lifelinePanelLayout = new javax.swing.GroupLayout(lifelinePanel);
        lifelinePanel.setLayout(lifelinePanelLayout);
        lifelinePanelLayout.setHorizontalGroup(
            lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lifelinePanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(backToQuestionButton)
                .addGap(109, 109, 109)
                .addComponent(chooseLifelineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(quitButton5)
                .addGap(128, 128, 128))
            .addGroup(lifelinePanelLayout.createSequentialGroup()
                .addGroup(lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lifelinePanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lifelineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lifelinePanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneOption)
                            .addComponent(audienceOption)
                            .addComponent(fiftyfiftyOption)))
                    .addGroup(lifelinePanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lifelinePanelLayout.setVerticalGroup(
            lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lifelinePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lifelineLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(fiftyfiftyOption)
                .addGap(32, 32, 32)
                .addComponent(phoneOption)
                .addGap(33, 33, 33)
                .addComponent(audienceOption)
                .addGap(52, 52, 52)
                .addGroup(lifelinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseLifelineButton)
                    .addComponent(backToQuestionButton)
                    .addComponent(quitButton5))
                .addGap(96, 96, 96))
        );

        parentPanel.add(lifelinePanel, "card6");

        gameEndPanel.setBackground(new java.awt.Color(0, 0, 0));

        gameEndLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        gameEndLabel.setForeground(new java.awt.Color(255, 204, 0));
        gameEndLabel.setText("GAME OVER/ You've won");

        jScrollPane2.setViewportView(jTextPane1);

        moneyWonLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        moneyWonLabel.setForeground(new java.awt.Color(255, 255, 255));
        moneyWonLabel.setText("You've Won: ");

        moneyWonValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        moneyWonValue.setForeground(new java.awt.Color(255, 255, 255));
        moneyWonValue.setText("jLabel2");

        quitButton3.setText("Quit");
        quitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton3ActionPerformed(evt);
            }
        });

        menuButton2.setText("Menu");
        menuButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameEndPanelLayout = new javax.swing.GroupLayout(gameEndPanel);
        gameEndPanel.setLayout(gameEndPanelLayout);
        gameEndPanelLayout.setHorizontalGroup(
            gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(menuButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitButton3)
                .addGap(165, 165, 165))
            .addGroup(gameEndPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(moneyWonLabel)
                .addGap(49, 49, 49)
                .addComponent(moneyWonValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameEndPanelLayout.createSequentialGroup()
                        .addComponent(gameEndLabel)
                        .addGap(102, 102, 102))))
        );
        gameEndPanelLayout.setVerticalGroup(
            gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameEndPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(gameEndLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyWonLabel)
                    .addComponent(moneyWonValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gameEndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton3)
                    .addComponent(menuButton2))
                .addGap(25, 25, 25))
        );

        parentPanel.add(gameEndPanel, "card5");

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 440));
        parentPanel.getAccessibleContext().setAccessibleName("parentPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        database.addToDatabase(player.getName(), player.getMoney());
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void instructionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionButtonActionPerformed
        JOptionPane.showMessageDialog(null, "- To answer a question please type the letter corresponding to the answer and hit enter.\n"
                + "- To use a lifeline, type \"YES\" when prompted and pick a lifeline from the lifelines shown.\n"
                + "- To walk away with the money, enter \"Q\" at any time and press enter.\n"
                + "- If you get an answer wrong, your money won will decrease to the corresponding thresholds (100, 1000, 32000).\n"
                + "- If you get a question wrong at the threshold, the game will end.\n"
                + "- If you're ready to become a millionaire, type \"START\" and hit enter.", "Instructions", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_instructionButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(leaderboardPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        database = new LeaderBoardDatabase();
        database.getDatabase(leaderboardTextPane);
    }//GEN-LAST:event_playButtonActionPerformed

    private void quitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton2ActionPerformed
        database.addToDatabase(player.getName(), player.getMoney());
        System.exit(0);
    }//GEN-LAST:event_quitButton2ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void quitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton3ActionPerformed
        database.addToDatabase(player.getName(), player.getMoney());
        System.exit(0);
    }//GEN-LAST:event_quitButton3ActionPerformed

    private void menuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton2ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(menuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_menuButton2ActionPerformed

    private void useLifelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useLifelineActionPerformed
        parentPanel.removeAll();
        parentPanel.add(lifelinePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
       
    }//GEN-LAST:event_useLifelineActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (!playerNameTextField.getText().equalsIgnoreCase("") && !playerNameTextField.getText().equalsIgnoreCase("Name")){
            parentPanel.removeAll();
            parentPanel.add(questionPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
            
            player.setName(playerNameTextField.getText());
            database.addToDatabase(player.getName(), player.getMoney());
            currentPointsTextPane.setText(Integer.toString(player.getMoney()));
            game.playGame(currentQuestionTextField, currentPointsTextPane, optionA, optionB, optionC, optionD);
            
        }
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void backToQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToQuestionButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(questionPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_backToQuestionButtonActionPerformed

    private void quitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton5ActionPerformed
        database.addToDatabase(player.getName(), player.getMoney());
        System.exit(0);
    }//GEN-LAST:event_quitButton5ActionPerformed

    private void playerNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerNameTextFieldFocusGained
        playerNameTextField.setText("");
    }//GEN-LAST:event_playerNameTextFieldFocusGained

    private void playerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameTextFieldActionPerformed
       
       
//        player = new PlayerInfo(playerNameTestField.getText(), 0);
    }//GEN-LAST:event_playerNameTextFieldActionPerformed

    private void lockAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockAnswerActionPerformed
        boolean correct;
        int money;
        String[] chosenAnswerArray = buttonGroup1.getSelection().getActionCommand().split(":");
        if (chosenAnswerArray[0].equalsIgnoreCase(game.getAnswer())){
           correct = true;
           JOptionPane.showMessageDialog(null, "Correct Answer");
        }
        else {
            correct = false;
            JOptionPane.showMessageDialog(null, "Wrong Answer, the correct answer was: " + game.getAnswer() );
            
        }
        updateMoneyWon.setMoneyWon(correct, player);
        if (updateMoneyWon.answerWrongAtThreshhold(player) || player.getMoney() == 0){
            parentPanel.removeAll();
            parentPanel.add(gameEndPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
        }
        else if (player.getMoney() == 1000000){
            parentPanel.removeAll();
            parentPanel.add(gameEndPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
            JOptionPane.showMessageDialog(null, "Congratulations you've won a MILLION dollars!!! (Note: In virtual money)\n");
        }
        currentPointsTextPane.setText(Integer.toString(player.getMoney()));
        // add to database
    }//GEN-LAST:event_lockAnswerActionPerformed

    private void quitButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton4ActionPerformed
        database.addToDatabase(player.getName(), player.getMoney());
        System.exit(0);
    }//GEN-LAST:event_quitButton4ActionPerformed

    private void nextQuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuesButtonActionPerformed
        
    }//GEN-LAST:event_nextQuesButtonActionPerformed

    private void optionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBActionPerformed
        optionB.setActionCommand(optionB.getText());
    }//GEN-LAST:event_optionBActionPerformed

    private void optionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionAActionPerformed
        optionA.setActionCommand(optionA.getText());
    }//GEN-LAST:event_optionAActionPerformed

    private void optionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCActionPerformed
        optionC.setActionCommand(optionC.getText());
    }//GEN-LAST:event_optionCActionPerformed

    private void optionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionDActionPerformed
        optionD.setActionCommand(optionC.getText());
    }//GEN-LAST:event_optionDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton audienceOption;
    private javax.swing.JButton backToQuestionButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chooseLifelineButton;
    private javax.swing.JTextPane currentPointsTextPane;
    private javax.swing.JTextField currentQuestionTextField;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JRadioButton fiftyfiftyOption;
    private javax.swing.JLabel gameEndLabel;
    private javax.swing.JPanel gameEndPanel;
    private javax.swing.JButton instructionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel leaderboardPanel;
    private javax.swing.JTextPane leaderboardTextPane;
    private javax.swing.JLabel leaderboardTitleLabel;
    private javax.swing.JLabel lifelineLabel;
    private javax.swing.JPanel lifelinePanel;
    private javax.swing.JButton lockAnswer;
    private javax.swing.JLabel logo;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton menuButton2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel moneyWonLabel;
    private javax.swing.JLabel moneyWonValue;
    private javax.swing.JButton nextQuesButton;
    private javax.swing.JRadioButton optionA;
    private javax.swing.JRadioButton optionB;
    private javax.swing.JRadioButton optionC;
    private javax.swing.JRadioButton optionD;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JRadioButton phoneOption;
    private javax.swing.JButton playButton;
    private java.awt.TextField playerNameTextField;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton quitButton2;
    private javax.swing.JButton quitButton3;
    private javax.swing.JButton quitButton4;
    private javax.swing.JButton quitButton5;
    private javax.swing.JButton startButton;
    private javax.swing.JButton useLifeline;
    // End of variables declaration//GEN-END:variables

    
}
